Revert "Add test data for unit-tests"
This reverts commit 064ab6399119a48e38191a74a9b93231fba71fb6.

That commit broke tests:

Failed tests:   testDesktopPageviewCount(org.wikimedia.analytics.kraken.pig.ComparePageviewDefinitionsTest): expected:<([1,5],2)> but was:<([0,0],2)>
  testMobilePageviewCount(org.wikimedia.analytics.kraken.pig.ComparePageviewDefinitionsTest): expected:<(1[4,16],18)> but was:<(1[,1],18)>

Change-Id: Ic625abd260986735158e6084caeb513b0fdabc9b